#include "toolpath/core/GCodeWriter.hpp"

#include <iomanip>
#include <sstream>

namespace toolpath::core {

std::string GCodeWriter::writeGrblProgram(const Toolpath& toolpath, const Tool& tool) const
{
    std::ostringstream out;
    out << std::fixed << std::setprecision(3);
    out << "(Generated by Toolpath Studio)\n";
    out << "G21\n";
    out << "G90\n";
    out << "G17\n";
    out << "M3 S" << static_cast<int>(tool.spindleRpm) << "\n";

    for (const auto& move : toolpath.moves) {
        switch (move.type) {
        case MoveType::Rapid:
            out << "G0";
            break;
        case MoveType::Plunge:
        case MoveType::Cut:
            out << "G1";
            break;
        }

        out << " X" << move.position.x()
            << " Y" << move.position.y()
            << " Z" << move.position.z();

        if (move.type != MoveType::Rapid && move.feedRateMmMin > 0.0) {
            out << " F" << move.feedRateMmMin;
        }

        out << "\n";
    }

    out << "M5\n";
    out << "G0 Z5.000\n";
    out << "M30\n";
    return out.str();
}

} // namespace toolpath::core

